

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Dimension; 
import java.awt.Toolkit;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author Michel
 */
public class frm_VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frm_VentanaPrincipal
     */
    public frm_VentanaPrincipal() {
        initComponents();
        centraVentana();        
    }  
    
public void centraVentana() {
Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
Dimension frameSize = getSize();
if (frameSize.height > screenSize.height) {
    frameSize.height = screenSize.height;
}
if (frameSize.width > screenSize.width) { frameSize.width = screenSize.width; }
setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        Metodo = new javax.swing.JMenu();
        metodoCongruencialLineal = new javax.swing.JMenuItem();
        metodoCongruencialMultiplicativo = new javax.swing.JMenuItem();
        chiCuadrado = new javax.swing.JMenu();
        menu_generador = new javax.swing.JMenuItem();
        menu_local = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TP N°1 - Simulación");
        setSize(new java.awt.Dimension(150, 150));

        Metodo.setMnemonic('f');
        Metodo.setText("Método");

        metodoCongruencialLineal.setText("Congruencial Lineal");
        metodoCongruencialLineal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                metodoCongruencialLinealMouseClicked(evt);
            }
        });
        metodoCongruencialLineal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metodoCongruencialLinealActionPerformed(evt);
            }
        });
        Metodo.add(metodoCongruencialLineal);

        metodoCongruencialMultiplicativo.setText("Congruencial Multiplicativo");
        metodoCongruencialMultiplicativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metodoCongruencialMultiplicativoActionPerformed(evt);
            }
        });
        Metodo.add(metodoCongruencialMultiplicativo);

        menuBar.add(Metodo);

        chiCuadrado.setMnemonic('e');
        chiCuadrado.setText("Chi Cuadrado");
        chiCuadrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chiCuadradoMouseClicked(evt);
            }
        });
        chiCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chiCuadradoActionPerformed(evt);
            }
        });

        menu_generador.setText("Generador");
        menu_generador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_generadorActionPerformed(evt);
            }
        });
        chiCuadrado.add(menu_generador);

        menu_local.setText("Local");
        menu_local.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_localActionPerformed(evt);
            }
        });
        chiCuadrado.add(menu_local);

        menuBar.add(chiCuadrado);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(427, 427, 427)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void metodoCongruencialLinealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_metodoCongruencialLinealMouseClicked
   // TODO add your handling code here:
    }//GEN-LAST:event_metodoCongruencialLinealMouseClicked

    private void metodoCongruencialLinealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metodoCongruencialLinealActionPerformed
            MetodoMultiplicativoLineal2 vp = new MetodoMultiplicativoLineal2();
            vp.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_metodoCongruencialLinealActionPerformed

    private void metodoCongruencialMultiplicativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metodoCongruencialMultiplicativoActionPerformed
    }//GEN-LAST:event_metodoCongruencialMultiplicativoActionPerformed

    private void chiCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chiCuadradoActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_chiCuadradoActionPerformed

    private void chiCuadradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chiCuadradoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_chiCuadradoMouseClicked

    private void menu_generadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_generadorActionPerformed
        frm_numerosEintervalos vp = new frm_numerosEintervalos();
        vp.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_menu_generadorActionPerformed

    private void menu_localActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_localActionPerformed
       frm_numerosEintervalos vp = new frm_numerosEintervalos();
       vp.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_menu_localActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu Metodo;
    private javax.swing.JMenu chiCuadrado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menu_generador;
    private javax.swing.JMenuItem menu_local;
    private javax.swing.JMenuItem metodoCongruencialLineal;
    private javax.swing.JMenuItem metodoCongruencialMultiplicativo;
    // End of variables declaration//GEN-END:variables

}